# Generated by Django 3.1.7 on 2021-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
