# Generated by Django 3.1.7 on 2021-04-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_phone_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='file',
            field=models.FileField(max_length=7000, null=True, upload_to=''),
        ),
    ]
